services:
  - type: web
    name: spinwin
    runtime: node
    rootDir: backend
    buildCommand: npm install --build-from-source
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://spinwin-607f.onrender.com
      - key: DASHBOARD_URL
        value: https://spinwin-607f.onrender.com
      - key: ALLOWED_ORIGIN
        value: "*"
      - key: DB_PATH
        value: ./spinwin.db
      - key: ADMIN_PASSWORD_HASH
        value: b433e3d25d8b55297297fc4a7bf1e020ccb8485af87d62e1f038917ef2496cf8
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_BASIC
        sync: false
      - key: STRIPE_PRICE_PRO
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
